name: Build Docker Image
on:
  push:
    tags:
      - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: checkout submodule
          run: git submodule update --init --recursive

        - name: Login to Hub
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.DOCKERHUB_REGISTRY }}
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Get version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

        - name: Build and Push
          run: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
            docker build -t ${{ secrets.DOCKER_IMAGE }}:${VERSION:1} .
            docker push ${{ secrets.DOCKER_IMAGE }}:${VERSION:1}
